/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/imoveis": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["AluguelIndexFiltroViewModel"];
          "text/json": components["schemas"]["AluguelIndexFiltroViewModel"];
          "application/*+json": components["schemas"]["AluguelIndexFiltroViewModel"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["RetornaImoveisModel"];
            "application/json": components["schemas"]["RetornaImoveisModel"];
            "text/json": components["schemas"]["RetornaImoveisModel"];
          };
        };
      };
    };
  };
  "/imoveis/{searchId}": {
    get: {
      parameters: {
        path: {
          searchId: string | null;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["RetornaImovelCodigoViewModel"];
            "application/json": components["schemas"]["RetornaImovelCodigoViewModel"];
            "text/json": components["schemas"]["RetornaImovelCodigoViewModel"];
          };
        };
      };
    };
  };
  "/imovel/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["FilterDetailsModel"];
            "application/json": components["schemas"]["FilterDetailsModel"];
            "text/json": components["schemas"]["FilterDetailsModel"];
          };
        };
      };
    };
  };
  "/api/Realstate": {
    get: {
      responses: {
        /** @description Success */
        200: never;
      };
    };
  };
  "/api/Realstate/Imoview": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["RentViewModel"];
          "text/json": components["schemas"]["RentViewModel"];
          "application/*+json": components["schemas"]["RentViewModel"];
        };
      };
      responses: {
        /** @description Success */
        200: never;
      };
    };
  };
  "/api/Realstate/Vista": {
    get: {
      parameters?: {
        query?: {
          imovel?: string | null;
          fields?: string[] | null;
        };
      };
      responses: {
        /** @description Success */
        200: never;
      };
    };
  };
  "/": {
    get: {
      responses: {
        /** @description Success */
        200: never;
      };
    };
  };
  "/categorias": {
    get: {
      parameters?: {
        query?: {
          tpo_negocio?: number;
          finalidade?: string | null;
          slugs?: string | null;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["RetornaCategoriaBusca"][];
            "application/json": components["schemas"]["RetornaCategoriaBusca"][];
            "text/json": components["schemas"]["RetornaCategoriaBusca"][];
          };
        };
      };
    };
  };
  "/categorias/filtros": {
    get: {
      parameters?: {
        query?: {
          Finalidade?: string | null;
          Categoria?: string | null;
          Negocio?: number;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Filtro"];
            "application/json": components["schemas"]["Filtro"];
            "text/json": components["schemas"]["Filtro"];
          };
        };
      };
    };
  };
  "/categorias/slug": {
    get: {
      parameters?: {
        query?: {
          ids?: string | null;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["RetornaCategoriaSlug"];
            "application/json": components["schemas"]["RetornaCategoriaSlug"];
            "text/json": components["schemas"]["RetornaCategoriaSlug"];
          };
        };
      };
    };
  };
  "/categoria/{slug}": {
    get: {
      parameters: {
        path: {
          slug: string | null;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["RetornaCategoriaBusca"];
            "application/json": components["schemas"]["RetornaCategoriaBusca"];
            "text/json": components["schemas"]["RetornaCategoriaBusca"];
          };
        };
      };
    };
  };
  "/localizacoes": {
    get: {
      parameters?: {
        query?: {
          Term?: string | null;
          Bairro?: boolean;
          Cidade?: boolean;
          Logradouro?: boolean;
          Estado?: boolean;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["RetornaLocalizacoes"];
            "application/json": components["schemas"]["RetornaLocalizacoes"];
            "text/json": components["schemas"]["RetornaLocalizacoes"];
          };
        };
      };
    };
  };
  "/localizacoes/{slug}": {
    get: {
      parameters: {
        path: {
          slug: string | null;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["RetornaLocalizacaoViewModel"];
            "application/json": components["schemas"]["RetornaLocalizacaoViewModel"];
            "text/json": components["schemas"]["RetornaLocalizacaoViewModel"];
          };
        };
      };
    };
  };
  "/localizacoes/bairro/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Bairro"];
            "application/json": components["schemas"]["Bairro"];
            "text/json": components["schemas"]["Bairro"];
          };
        };
      };
    };
  };
  "/localizacoes/cidade/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Cidade"];
            "application/json": components["schemas"]["Cidade"];
            "text/json": components["schemas"]["Cidade"];
          };
        };
      };
    };
  };
  "/localizacoes/logradouro/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Logradouro"];
            "application/json": components["schemas"]["Logradouro"];
            "text/json": components["schemas"]["Logradouro"];
          };
        };
      };
    };
  };
  "/localizacoes/estado/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Estado"];
            "application/json": components["schemas"]["Estado"];
            "text/json": components["schemas"]["Estado"];
          };
        };
      };
    };
  };
  "/localizacoes/bairros": {
    get: {
      parameters?: {
        query?: {
          Id?: number;
          Slug?: string | null;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Bairro"][];
            "application/json": components["schemas"]["Bairro"][];
            "text/json": components["schemas"]["Bairro"][];
          };
        };
      };
    };
  };
  "/localizacoes/logradouros": {
    get: {
      parameters?: {
        query?: {
          Id?: number;
          Slug?: string | null;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Bairro"][];
            "application/json": components["schemas"]["Bairro"][];
            "text/json": components["schemas"]["Bairro"][];
          };
        };
      };
    };
  };
  "/lead": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["DadosFormularioViewModel"];
          "text/json": components["schemas"]["DadosFormularioViewModel"];
          "application/*+json": components["schemas"]["DadosFormularioViewModel"];
        };
      };
      responses: {
        /** @description Success */
        200: never;
      };
    };
  };
  "/visitas": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["DadosVisitasViewModel"];
          "text/json": components["schemas"]["DadosVisitasViewModel"];
          "application/*+json": components["schemas"]["DadosVisitasViewModel"];
        };
      };
      responses: {
        /** @description Success */
        200: never;
      };
    };
  };
  "/api/System/PopulateImoview": {
    get: {
      parameters?: {
        query?: {
          page?: number;
          ignoraData?: boolean;
          populaLocalizacoes?: boolean;
        };
      };
      responses: {
        /** @description Success */
        200: never;
      };
    };
  };
  "/api/System/PopulateVista": {
    get: {
      parameters?: {
        query?: {
          page?: number;
          ignoraData?: boolean;
          populaLocalizacoes?: boolean;
        };
      };
      responses: {
        /** @description Success */
        200: never;
      };
    };
  };
  "/api/System/PopulateCorretor": {
    get: {
      parameters?: {
        query?: {
          page?: number;
        };
      };
      responses: {
        /** @description Success */
        200: never;
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    FilterMinMax: {
      /** Format: int32 */
      min?: number;
      /** Format: int32 */
      max?: number;
    };
    AluguelIndexFiltroViewModel: {
      /** Format: int32 */
      negocio: number;
      finalidade: string;
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      id_campanha?: number | null;
      /** Format: int32 */
      id_filtro?: number;
      /** Format: int32 */
      cidade?: number;
      /** Format: int32 */
      bairro?: number;
      /** Format: int32 */
      estado?: number;
      categoria_mobile?: string | null;
      valor?: components["schemas"]["FilterMinMax"];
      area?: components["schemas"]["FilterMinMax"];
      order?: string | null;
      endereco?: string | null;
      caracteristica?: string | null;
      categorias?: number[] | null;
      caracImovel?: string[] | null;
      caracCondominio?: string[] | null;
      caracOutras?: string[] | null;
      /** Format: int32 */
      tipo?: number;
      /** Format: int32 */
      tipo_negocio?: number;
      /** Format: int32 */
      numeroquartos?: number;
      /** Format: int32 */
      numerobanheiros?: number;
      /** Format: int32 */
      numerovagas?: number;
      /** Format: int32 */
      numerosuites?: number;
      churrasqueira?: boolean;
      portaria24horas?: boolean;
      /** Format: int32 */
      numeroelevador?: number;
      piscina?: boolean;
      academia?: boolean;
      playground?: boolean;
      sacada?: boolean;
      patio?: boolean;
      pet_friendly?: boolean;
      salaofestas?: boolean;
      tour?: boolean;
      desconto?: boolean;
      prato_cheio?: boolean;
      virada_chave?: boolean;
      exclusivo?: boolean;
      video?: boolean;
      mobiliado?: boolean;
      distancia?: boolean;
    };
    FotoModel: {
      foto?: string | null;
    };
    CategoriaViewModel: {
      nome?: string | null;
      /** Format: int32 */
      id?: number;
    };
    CorretorViewModel: {
      /** Format: int32 */
      codigo?: number;
      nome?: string | null;
      email?: string | null;
      celular?: string | null;
      foto?: string | null;
    };
    TagViewModel: {
      nome?: string | null;
      cor_de_texto?: string | null;
      cor_de_fundo?: string | null;
    };
    FilterDetailsModel: {
      /** Format: int32 */
      num_fotos?: number;
      imagem?: string | null;
      fotos?: components["schemas"]["FotoModel"][] | null;
      whatsapp?: string | null;
      phone?: string | null;
      descricao_interna?: string | null;
      valor_txt?: string | null;
      /** Format: double */
      valor_num?: number;
      valor_tabela_txt?: string | null;
      valor_condominio_txt?: string | null;
      valor_iptu_txt?: string | null;
      categoria?: components["schemas"]["CategoriaViewModel"];
      codigo?: string | null;
      bairro?: string | null;
      cidade?: string | null;
      /** Format: int32 */
      tipo?: number;
      desconto?: string | null;
      carencia?: string | null;
      flag?: string | null;
      telefone_primario?: string | null;
      telefone_secundario?: string | null;
      /** Format: int32 */
      id_campanha?: number | null;
      id?: string | null;
      /** Format: int32 */
      quartos?: number;
      area_total_txt?: string | null;
      /** Format: double */
      area_util_num?: number;
      /** Format: int32 */
      negocio?: number;
      endereco?: string | null;
      /** Format: int32 */
      cidade_id?: number;
      /** Format: int32 */
      bairro_id?: number;
      /** Format: int32 */
      estado_id?: number;
      uf?: string | null;
      numero?: string | null;
      /** Format: int32 */
      vagas?: number;
      caracteristicas_imovel?: string[] | null;
      caracteristicas_condominio?: string[] | null;
      promo_extra?: string | null;
      video?: string | null;
      tour?: string | null;
      exclusivo?: string | null;
      informacao?: string | null;
      titulo?: string | null;
      telefone?: string | null;
      url?: string | null;
      favorito?: string | null;
      /** Format: int32 */
      banheiros?: number;
      tag_tour?: boolean;
      tag_carencia?: boolean;
      tag_exclusivo?: boolean;
      tag_valorTabela?: boolean;
      /** Format: int32 */
      campanha_id?: number;
      /** Format: int32 */
      suites?: number;
      churrasqueira?: boolean;
      portaria24hrs?: boolean;
      /** Format: int32 */
      elevadores?: number;
      /** Format: double */
      valor_anterior_num?: number;
      valor_anterior_txt?: string | null;
      /** Format: double */
      valor_total_num?: number;
      valor_total_txt?: string | null;
      /** Format: double */
      renda_minima_num?: number;
      renda_minima_txt?: string | null;
      /** Format: double */
      custos_servicos_num?: number;
      custos_servicos_txt?: string | null;
      /** Format: double */
      seguro_fogo_num?: number;
      seguro_fogo_txt?: string | null;
      desconto_percentual?: string | null;
      corretor?: components["schemas"]["CorretorViewModel"];
      tag?: components["schemas"]["TagViewModel"][] | null;
    };
    PaginasModel: {
      current?: string | null;
      /** Format: int32 */
      pages?: number;
    };
    RetornaImoveisModel: {
      all?: string[] | null;
      imoveis?: components["schemas"]["FilterDetailsModel"][] | null;
      sugestoes?: components["schemas"]["FilterDetailsModel"][] | null;
      paginacao?: components["schemas"]["PaginasModel"];
      /** Format: int32 */
      total?: number;
    };
    ImovelCodigoViewModel: {
      codigoImovel?: string | null;
      url?: string | null;
    };
    RetornaImovelCodigoViewModel: {
      imoveisAluguel?: components["schemas"]["ImovelCodigoViewModel"][] | null;
      imoveisComprar?: components["schemas"]["ImovelCodigoViewModel"][] | null;
    };
    RentViewModel: {
      codigoImovel: string;
      token: string;
    };
    RetornaCategoriaBusca: {
      /** Format: int32 */
      id?: number;
      finalidade?: string | null;
      slug?: string | null;
      nome?: string | null;
      negocio?: string | null;
      plural?: string | null;
    };
    Propriedade: {
      id?: string | null;
      text?: string | null;
      type?: string | null;
      values?: string[] | null;
    };
    CaracteristicasImovel: {
      id?: string | null;
      text?: string | null;
    };
    Valores: {
      /** Format: double */
      maxValor?: number;
      /** Format: double */
      maxArea?: number;
    };
    Filtro: {
      finalidade?: string | null;
      categoria?: string | null;
      propriedades?: components["schemas"]["Propriedade"][] | null;
      caracteristicasImovel?:
        | components["schemas"]["CaracteristicasImovel"][]
        | null;
      caracteristicasCondominio?:
        | components["schemas"]["CaracteristicasImovel"][]
        | null;
      valores?: components["schemas"]["Valores"];
    };
    RetornaCategoriaSlug: {
      slug?: string | null;
    };
    Estado: {
      /** Format: int32 */
      id?: number;
      nome?: string | null;
      slug?: string | null;
      uf?: string | null;
    };
    Cidade: {
      /** Format: int32 */
      id?: number;
      nome?: string | null;
      slug?: string | null;
      uf?: string | null;
      estado?: components["schemas"]["Estado"];
    };
    Bairro: {
      /** Format: int32 */
      id?: number;
      nome?: string | null;
      slug?: string | null;
      cidade?: components["schemas"]["Cidade"];
    };
    Logradouro: {
      /** Format: int32 */
      id?: number;
      nome?: string | null;
      slug?: string | null;
      latitude?: string | null;
      longitude?: string | null;
      bairro?: components["schemas"]["Bairro"];
    };
    RetornaLocalizacoes: {
      bairros?: components["schemas"]["Bairro"][] | null;
      cidades?: components["schemas"]["Cidade"][] | null;
      logradouros?: components["schemas"]["Logradouro"][] | null;
      estados?: components["schemas"]["Estado"][] | null;
    };
    BreadcrumbItem: {
      nome?: string | null;
      slug?: string | null;
      tipo?: string | null;
    };
    RetornaLocalizacaoViewModel: {
      tipo?: string | null;
      /** Format: int32 */
      id?: number;
      nome?: string | null;
      slug?: string | null;
      breadcrumb?: components["schemas"]["BreadcrumbItem"][] | null;
    };
    DadosFormularioViewModel: {
      nome?: string | null;
      email?: string | null;
      telefone?: string | null;
      mensagem?: string | null;
      aceita_Termos?: boolean;
      aceita_notificacao?: boolean;
      campanha?: string | null;
      source?: string | null;
      /** Format: int32 */
      codigo_imovel?: number;
      /** Format: int32 */
      negocio?: number;
      /** Format: int32 */
      corretor?: number;
    };
    DadosVisitasViewModel: {
      /** Format: int32 */
      codigo_Imovel?: number;
      /** Format: int32 */
      negocio?: number;
      nome_Interessado?: string | null;
      email_Interessado?: string | null;
      telefone_Interessado?: string | null;
      /** Format: date-time */
      data_de_Visita?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
